apiVersion: v1
kind: Service
metadata:
  name: ambienttracker-service
spec:
  type: LoadBalancer
  selector:
    app: ambienttracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
